export const IMAGE_URL_REQUEST_TO_ADD_MARIO = 'IMAGE_URL_REQUEST_TO_ADD_MARIO'
export const IMAGE_URL_SUCCESS_TO_ADD_MARIO = 'IMAGE_URL_SUCCESS_TO_ADD_MARIO'

export const MARIO_IMAGE_URL = '/images/mario.jpg'